name: Docker
on:
  pull_request:
    types: [closed]
jobs:
  delete-preview-deployment:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Get application ID of PR
        run: |
          RESPONSE=$(curl -X GET \
          -H "Authorization: Bearer ${{ secrets.WATCHDOG_API_KEY }}" \
          "https://watchdog.svuit.org/application_id?repo_name=SVUIT/img2md&pr_number=6")
          echo "API Response: $RESPONSE"
          APPLICATION_ID=$(echo "$RESPONSE" | jq -r '.application_id')
          echo "APPLICATION_ID=$APPLICATION_ID" >> $GITHUB_ENV
      - name: Call API to delete PR data
        run: |
          curl -X POST "https://dokploy.svuit.org/api/application.delete" \
            -H "Authorization: Bearer ${{secrets.TOKEN}}" \
            -H "Content-Type: application/json" \
            -d '{
              "applicationId": "${{env.APPLICATION_ID}}"
            }'
  delete-package:
    runs-on: ubuntu-latest
    steps:
      - name: Delete GitHub Package
        run: |
          RESPONSE=$(curl -X DELETE \
          -H "Authorization: Bearer ${{secrets.TOKEN}}" \
          -H "Accept: application/vnd.github.v3+json" \
          "https://api.github.com/users/Thanh8804/packages/container/img2md%2F${{ github.event.pull_request.number }}")
          echo "API Response: $RESPONSE"
          if echo "$RESPONSE" | jq -e .message >/dev/null 2>&1; then
            echo "Error: $(echo "$RESPONSE" | jq -r '.message')"
            exit 1
          fi
